version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8080:8080"
    env_file:
      - ./user-service/.env
    restart: always

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    env_file:
      - ./order-service/.env
    restart: always
    depends_on:
      - user-service

  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "8082:8082"
    env_file:
      - ./payment-service/.env
    restart: always
    depends_on:
      - user-service
      - order-service
