basePath: /
definitions:
  dto.BookingRequest:
    properties:
      days:
        type: integer
      room_id:
        type: integer
      start_date:
        type: string
    required:
    - days
    - room_id
    - start_date
    type: object
  dto.BookingResponse:
    properties:
      category:
        type: string
      message:
        type: string
      room_name:
        type: string
      total_price:
        type: number
    type: object
  dto.RoomResponse:
    properties:
      category:
        type: string
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
    type: object
host: localhost:8081
info:
  contact: {}
  description: system booking mandaya hotels
  title: mandaya project API order-service
  version: "1.0"
paths:
  /rooms:
    get:
      consumes:
      - application/json
      description: Get a list of all available rooms with name, category, price, and
        stock.
      produces:
      - application/json
      responses:
        "200":
          description: List of rooms
          schema:
            items:
              $ref: '#/definitions/dto.RoomResponse'
            type: array
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all available rooms
      tags:
      - Rooms
  /rooms/booked:
    get:
      consumes:
      - application/json
      description: Fetch all rooms currently booked by the authenticated user, including
        payment status.
      produces:
      - application/json
      responses:
        "200":
          description: List of booked rooms with payment status
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
        "401":
          description: Unauthorized access
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get booked rooms for the authenticated user
      tags:
      - Rooms
  /rooms/booking:
    post:
      consumes:
      - application/json
      description: Book a room for a given number of days and start date.
      parameters:
      - description: Booking Request
        in: body
        name: booking
        required: true
        schema:
          $ref: '#/definitions/dto.BookingRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Booking Successful
          schema:
            $ref: '#/definitions/dto.BookingResponse'
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Room not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Booking failed
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Book a room
      tags:
      - Rooms
  /rooms/cancel/{id}:
    delete:
      consumes:
      - application/json
      description: Cancel a user's booking by booking ID. Only the owner of the booking
        can cancel it.
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Cancellation Successful
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "403":
          description: Not authorized to cancel this booking
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Booking not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Cancellation failed
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Cancel a booking
      tags:
      - Rooms
swagger: "2.0"
