basePath: /
host: localhost:8082
info:
  contact: {}
  description: system booking mandaya hotels
  title: mandaya project API order-service
  version: "1.0"
paths:
  /rooms/payment/{id}:
    post:
      consumes:
      - application/json
      description: Pay the total price of a booking with the user's balance and mark
        it as paid.
      parameters:
      - description: Booking ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Payment successful
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Insufficient balance or invalid request
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Booking not found
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Payment failed
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Pay for a booking
      tags:
      - Payments
swagger: "2.0"
