basePath: /
definitions:
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.LoginResponse:
    properties:
      token:
        type: string
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
host: localhost:8080
info:
  contact: {}
  description: system booking mandaya hotels
  title: mandaya project API user-service
  version: "1.0"
paths:
  /users/login:
    post:
      consumes:
      - application/json
      description: This endpoint allows users to login by providing email and password.
      parameters:
      - description: Login User
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.LoginResponse'
        "400":
          description: Invalid Request Parameters
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Invalid Password
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Invalid Generate Token
          schema:
            additionalProperties: true
            type: object
      summary: Login a user
      tags:
      - Users
  /users/register:
    post:
      consumes:
      - application/json
      description: Register a new user with the provided details.
      parameters:
      - description: Register User
        in: body
        name: register
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success message and user details
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Invalid Request Parameters
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Register Failed
          schema:
            additionalProperties: true
            type: object
      summary: Register a new user
      tags:
      - Users
swagger: "2.0"
